backend-image: &standard-build
  stage: build
  script:
  - "nix-build -A $CI_JOB_NAME"
  - "cp $(realpath result) result-copy"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - result-copy
    expire_in: 2 weeks

frontend-public: *standard-build
