services:
- docker
script:
- docker run -w /build -v `pwd`:/build:cached -it nixos/nix:2.3 /bin/sh -c "bin/build.sh `id -u` `id -g`"
- ls -aR build || true

deploy:
  provider: releases
  api_key:
    secure: TODO
  file:
  - "./build/frontend_public/frontend_public.js"
  - "./build/backend/backend-image.tar.gz"
  file_glob: true
  on:
    repo: tweedegolf/irma-call
    tags: true
  skip_cleanup: 'true'
