services:
- docker
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export DOCKER_TAG=$(git describe --abbrev=0)
- docker run -w /build -v `pwd`:/build:cached -it nixos/nix:2.3 /bin/sh -c "bin/build.sh
  `id -u` `id -g`"
- ls -aR build || true
deploy:
- provider: releases
  api_key:
    secure: JiUQ8qPFLmFJpBd4p3tmTCAGVtf7ILGNK/6wVXNg0JMjnj1NrhGivdGb8sNwN19gwGET0G9aCpiNF6AEeVF7VoHcMeF86kFZQ9fmlU12CeCl8420JOmr13+WzycTRWXqNNZ9sAu34D/Q//8Brartf/+tDdtaVr53WuAPttxsFx7/l0zgHNF2dBmRaLhdJBRWvnxkZTfPdVnEmK6i6ciw1oigJ9xGjrReUGJ1Jxny24gDNTdIXe4mVtgtrb6JaIAQFMgq237LtJ0HYaZMs4gXcoGjvV08HvJHQfdcnfuYK0CKJw97ZkeUC8F8kSVlhxVSVcFunltvVpaS2+y2GIpY03LK+FuaYWhqHkFelJ0gthJ4spgYZeUcDK4zKfwa7jO0zUFT2LD4NR4gtTxmRMJOQK8hKSsvZpn7QoN6yl+P3X/d3tCFjIGL8OPVh+iHYIiJulyAfekm5qNDJeonuTeg46mb2LFnipZW9TRHWcgJLKSaysx6amH45pgQXt5NtMQrfBaRugx03zfOAXazxv1NC0iymaZGpThkl2nduoObttfbGJ7Oie7So0M72aDnXl22S4Jlpym/NvMdqsW9UVS5ssopimMgybXOaynOKRr36kfta3zeps0mB6c0E+CX1GA7ZKdB4AYfJpOzJop4bp1QwOezEDogl3wqXtmCIb1HDhk=
  file:
  - "./build/frontend_public/frontend_public.js"
  - "./build/backend/backend-image.tar.gz"
  file_glob: true
  on:
    repo: tweedegolf/veilig-bellen
    tags: true
  skip_cleanup: 'true'
- provider: script
  script: bash bin/docker_push.sh
  on:
    repo: tweedegolf/veilig-bellen
  #   tags: true
env:
  global:
  - secure: niTmVx6e8f0naXOtDCgZ4i+LnuzvxNNdjXBjlsPMAi/ZdnSOXzOfHhIm9GokQE1+EVKjccDyXH1zcTRykx1BwTolP7D08ceRwVyRwvsZ/+9ufBtU5UfXAbjK5KxcxDbDKE9UfLtsXMJoS/M0QKD/2yS3UT4LycmWsVdzInozgEpeCsXkS443yWPPwb7sGjXatV+HLjduHjJ3oOinEpHD5TfxJJSumjZtNp7IQqfoBNi4C3s4XIaEGHkWq4k1Q5Fki76d+S+MsZzrisS2vIqEDcLJH9x8sBx32BffDEOunyRsEan+ZJa977vbViLQBV6pYuaJgOKhGplhJ/WPf7D8C53OcUmXOZGC9qeOR9n7tb3hSsiZCFtjxOPaRYVmDKY1zCikhjYnJtzhoTF1lBEdiKXuecTnPgAE500wVYpl4ALmsVGHDZfN36UtbtrQKXi+FZK6eFFACXbmBrkxUKWtJJqR95nfoYdeSQJzQn3JQxANXF1R/4Ov/suaa3zfi/iROp2aTHxi+Zv2WrDiaJRAfObp3dYks8cuynr2yawh2j7WUBMA70DlOa+ARQVk02rZ8GC7lY+AVohWdtCcpZTYpr+x4K0+ja0vpyho/kfwJ0geXEkYtcIdcna8Alckk2pc1wqN+epM1mdApnTmnmVekmPKLbgvke8vIeR4xs60aBM=
  - secure: BAZo5jRrARezoNlWZclNfUibmgq0QVkMrcPDGcCQNzIf3+LyqeguEgoMO3O0Vh99V2Cog2bbctmZiU/gX7y2UgyOtpUY+mSadj0Fq+Ntqs+bjtY6EYqqJu7nZvUr8QnZCA+EWBO3TasAqELMKWUGGq4hSkWRanJ2miE7sbZYLD2LxXu5kNEvEbtDrIUzBbUYxk+oZg3VaiTP2FNI4pmsgWxtuT79g7TT/N9mGCLwpD7i5c2JJa2zrBHsgUWNHq6bjNMmS139ZB6sR658cgA/TRtY3sGSL6EOJvp4kAZQtPpNSHMF1HFlL+X6YAhAwOp+x5lpvoBWztuWv6EJjaMfMmUfhZR/1lWYQLdOqN6lLM+gq1DD0k19Jt2zPmp6Gbd39yhfC+7T6cWBois77I+xK3d/0fti2Y3HSpYi425Pk7M48vDjNWa1Axl6w0yg/Ge0nAm1cVJ1ouWUoPe72ieTUAhlBeUVkLDV3T0N/cowlCQnRYNmubNwPrdi1rNHfGVsidICb6GdPuwd6f8X3vXV+429iyjMuA1lkZr6GNY3KlgTRh7XEFtuuLZZlgaE9kL9FDIafk136Qm9KrMzGJpigRD5+7vMbVWCkx1D0yuArKEJozrMtj6FhOswfWG6jteAy5n9/mMI4qsByRR5gDBL/dga+I6uDGD3XsLNkd3wC24=
