version: '3.3'
services:
  irma:
    build:
      dockerfile: './docker/irmago.Dockerfile'
      context: .
    expose: [8088]
    networks:
      - default
    ports: ["0.0.0.0:8088:8088"]
    command:
      - "irma"
      - "server"
      - "--verbose"
      - "--url=http://${HOST_LAN_IP}:8088"
      - "--no-auth=false"
      - '--requestors={"veilig-bellen":{"auth_method":"token","key":"12345"}}'

  nginx:
    image: nginx:1.17
    depends_on:
      - irma
      - backend
      - frontend_agents
      - frontend_panel
      - frontend_public
    volumes:
      - ".:/app:cached"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/certificates/server.pem:/etc/ssl/server.pem:ro"
      - "./docker/certificates/server.key:/etc/ssl/server.key:ro"
    ports: ["127.0.0.1:443:443", "127.0.0.1:80:80"]
    environment:
            TZ: Europe/Amsterdam
    networks:
        default:
            aliases:
              - backend.veiligbellen.test.tweede.golf
              - irma.veiligbellen.test.tweede.golf
              - agents.veiligbellen.test.tweede.golf
              - panel.veiligbellen.test.tweede.golf
              - public.veiligbellen.test.tweede.golf

  backend:
    build:
      dockerfile: './backend.Dockerfile'
      context: './docker'
      args:
        GO_VERSION: "1.14"
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
    user: "$USER_ID:$GROUP_ID"
    depends_on: [psql]
    volumes:
    - "./backend:/go/src/app:ro"
    - "./bin/:/bin/app/:ro"
    command:
    - "/bin/app/watch.sh"
    - "app"
    networks:
    - default
    environment:
    - BACKEND_DATABASE=postgres://tg@psql:5432/tg?sslmode=disable
    - BACKEND_LISTENADDRESS=:8080
    - BACKEND_IRMASERVER=http://irma:8088
    - BACKEND_IRMAHEADERKEY=Authorization
    - BACKEND_IRMAHEADERVALUE=12345
    - BACKEND_PHONENUMBER=+318000201001
    - BACKEND_PURPOSEMAP={"foo":[[["irma-demo.MijnOverheid.root.BSN"],["pbdf.gemeente.personalData.bsn"]]]}
    - BACKEND_CONNECT_ID=${CONNECT_ID}
    - BACKEND_CONNECT_SECRET=${CONNECT_SECRET}
    - BACKEND_CONNECT_INSTANCEID=503d5d31-de38-4803-bb39-02e98ee8891c
    - BACKEND_CONNECT_QUEUE=f3860ab3-8305-4862-940e-9f6b608f9530
    - BACKEND_CONNECT_REGION=eu-central-1
    ports: ["127.0.0.1:8080:8080"]
    expose: [8080]

  frontend_agents:
    build:
      dockerfile: './node.Dockerfile'
      context: './docker'
    user: "$USER_ID:$GROUP_ID"
    volumes:
    - "./frontend-agents:/app:cached"
    working_dir: "/app"
    command:
    - "/usr/local/bin/yarn"
    - "parcel"
    - "serve"
    - "--no-hmr"
    - "--no-autoinstall"
    - "src/index.html"
    environment:
    - HOME=/tmp/nodehome
    - BACKEND_URL=https://backend.veiligbellen.test.tweede.golf
    - CCP_HOST=sarif.awsapps.com
    networks:
    - default
    expose: [1234]

  frontend_panel:
    build:
      dockerfile: './node.Dockerfile'
      context: './docker'
    user: "$USER_ID:$GROUP_ID"
    volumes:
    - "./frontend-panel:/app:cached"
    working_dir: "/app"
    command:
    - "/usr/local/bin/yarn"
    - "parcel"
    - "serve"
    - "--no-hmr"
    - "--no-autoinstall"
    - "src/index.html"
    environment:
    - HOME=/tmp/nodehome
    - BACKEND_HOSTNAME=backend.veiligbellen.test.tweede.golf
    networks:
    - default
    expose: [1234]

  frontend_public:
    build:
      dockerfile: './node.Dockerfile'
      context: './docker'
    user: "$USER_ID:$GROUP_ID"
    volumes:
    - "./frontend-public:/app:cached"
    working_dir: "/app"
    command:
    - "/usr/local/bin/yarn"
    - "parcel"
    - "serve"
    - "--no-hmr"
    - "--no-autoinstall"
    - "src/example.html"
    environment:
    - HOME=/tmp/nodehome
    - BACKEND_HOST=backend.veiligbellen.test.tweede.golf
    - PURPOSE=foo
    - IRMAJS_LANGUAGE=nl
    networks:
    - default
    expose: [1234]

  psql:
    image: "postgres:12"
    environment:
        POSTGRES_USER: tg
        POSTGRES_DB: tg
        TZ: Europe/Amsterdam
        POSTGRES_HOST_AUTH_METHOD: trust
    ports: ["127.0.0.1:5433:5432"]
    networks: [default]

networks:
  default: ~
