version: '3.3'
services:
  irma:
    build:
      dockerfile: './docker/irmago.Dockerfile'
      context: .
    expose: [8088]
    networks:
      - default
    ports: ["0.0.0.0:8088:8088"]
    command: ["irma", "server", "-v", "--url", "http://${HOST_LAN_IP}:8088"]

  nginx:
    image: nginx:1.17
    depends_on:
      - irma
      - backend
      - frontend_agents
      - frontend_panel
      - frontend_public
    volumes:
      - ".:/app:cached"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/certificates/server.pem:/etc/ssl/server.pem:ro"
      - "./docker/certificates/server.key:/etc/ssl/server.key:ro"
    ports: ["127.0.0.1:443:443", "127.0.0.1:80:80"]
    environment:
            TZ: Europe/Amsterdam
    networks:
        default:
            aliases:
              - backend.veiligbellen.test.tweede.golf
              - irma.veiligbellen.test.tweede.golf
              - agents.veiligbellen.test.tweede.golf
              - panel.veiligbellen.test.tweede.golf
              - public.veiligbellen.test.tweede.golf

  backend:
    build:
      dockerfile: './docker/backend.Dockerfile'
      context: .
      args:
        GO_VERSION: "1.14"
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
    user: "$USER_ID:$GROUP_ID"
    depends_on: [psql]
    volumes:
    - "./backend:/go/src/app:cached"
    - "./bin/:/bin/app/:cached"
    command:
    - "/bin/app/watch.sh"
    - "app"
    - "--database=postgres://tg@psql:5432/tg?sslmode=disable"
    - "--listen-address=:8080"
    - "--irma-server=http://irma:8088"
    - "--phone-number=+318000227348"
    - '--purpose-map={"foo":[[["irma-demo.MijnOverheid.root.BSN"],["pbdf.gemeente.personalData.bsn"]]]}'
    networks:
      - default
    ports: ["127.0.0.1:8080:8080"]
    expose: [8080]

  frontend_agents:
    image: "node:buster-slim"
    user: "$USER_ID:$GROUP_ID"
    volumes:
    - "./frontend-agents:/app:cached"
    working_dir: "/app"
    command:
    - "/usr/local/bin/yarn"
    - "parcel"
    - "serve"
    - "--no-hmr"
    - "src/index.html"
    environment:
    - HOME=/tmp/nodehome
    - BACKEND_URL=https://backend.veiligbellen.test.tweede.golf
    - CCP_HOST=sarif.awsapps.com
    networks:
    - default
    expose: [1234]

  frontend_panel:
    image: "node:buster-slim"
    user: "$USER_ID:$GROUP_ID"
    volumes:
    - "./frontend-panel:/app:cached"
    working_dir: "/app"
    command:
    - "/usr/local/bin/yarn"
    - "parcel"
    - "serve"
    - "--no-hmr"
    - "src/index.html"
    environment:
    - HOME=/tmp/nodehome
    - BACKEND_HOSTNAME=backend.veiligbellen.test.tweede.golf
    networks:
    - default
    expose: [1234]


  frontend_public:
    image: "node:buster-slim"
    user: "$USER_ID:$GROUP_ID"
    volumes:
    - "./frontend-public:/app:cached"
    working_dir: "/app"
    command:
    - "/usr/local/bin/yarn"
    - "parcel"
    - "serve"
    - "--no-hmr"
    - "src/example.html"
    environment:
    - HOME=/tmp/nodehome
    - BACKEND_URL=https://backend.veiligbellen.test.tweede.golf
    - PURPOSE=foo
    networks:
    - default
    expose: [1234]

  psql:
    image: "postgres:12"
    environment:
        POSTGRES_USER: tg
        POSTGRES_DB: tg
        TZ: Europe/Amsterdam
        POSTGRES_HOST_AUTH_METHOD: trust
    ports: ["127.0.0.1:5433:5432"]
    networks: [default]

networks:
  default: ~
