version: '3.3'
services:
  
  irma:
    build:
      dockerfile: './docker/irmago.Dockerfile'
      context: .
    expose: [8088]
    networks:
      - default

  nginx:
    image: nginx:1.17
    depends_on:
      - irma
      - backend
    volumes:
      - ".:/app:cached"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/certificates/op-shop-test.pem:/etc/ssl/op-shop-test.pem:ro"
      - "./docker/certificates/op-shop-test.key:/etc/ssl/op-shop-test.key:ro"
    ports: ["127.0.0.1:443:443", "127.0.0.1:80:80", "127.0.0.1:8088:8088"]
    environment:
            TZ: Europe/Amsterdam
    networks:
        default:
            aliases:
              - veilig.bellen.test
  backend:
    build:
      dockerfile: './docker/backend.Dockerfile'
      context: .
      args:
        GO_VERSION: "1.14"
    volumes:
    - "./backend:/go/src/app:cached"
    - "./bin/:/bin/app/:cached"
    # user: '$USER_ID:$GROUP_ID'
    command: ["/bin/app/watch.sh", "main.go"]
    networks:
      - default
networks:
  default: ~