version: '3.3'
services:
  irma:
    build:
      dockerfile: './docker/irmago.Dockerfile'
      context: .
    expose: [8088]
    networks:
      - default
    ports: ["0.0.0.0:8088:8088"]
    command: ["irma", "server", "-v", "--url", "http://${HOST_LAN_IP}:8088"]

  nginx:
    image: nginx:1.17
    depends_on:
      - irma
      - backend
    volumes:
      - ".:/app:cached"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/certificates/server.pem:/etc/ssl/server.pem:ro"
      - "./docker/certificates/server.key:/etc/ssl/server.key:ro"
    ports: ["127.0.0.1:443:443", "127.0.0.1:80:80"]
    environment:
            TZ: Europe/Amsterdam
    networks:
        default:
            aliases:
              - backend.veiligbellen.test.tweede.golf
              - irma.veiligbellen.test.tweede.golf
  backend:
    build:
      dockerfile: './docker/backend.Dockerfile'
      context: .
      args:
        GO_VERSION: "1.14"
    user: "$USER_ID:$GROUP_ID"
    depends_on: [psql]
    volumes:
    - "./backend:/go/src/app:cached"
    - "./bin/:/bin/app/:cached"
    command: ["/bin/app/watch.sh", "app"]
    environment:
      POSTGRES_URL: "psql://tg@psql:5432/tg"
    networks:
      - default
    ports: ["127.0.0.1:8080:8080"]
    expose: [8080]

  psql:
    image: "postgres:12"
    environment:
        POSTGRES_USER: tg
        POSTGRES_DB: tg
        TZ: Europe/Amsterdam
        POSTGRES_HOST_AUTH_METHOD: trust
    ports: ["127.0.0.1:5432:5432"]
    networks: [default]
networks:
  default: ~
  